version: '3.9'

services:
  api:
      build:
        context: ../
        dockerfile: .docker/Dockerfile
      entrypoint: ["/bin/sh", "-c"]
      command:
        - |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py loaddata ./utils/builtin_tiers.json
          python manage.py shell < ./utils/create_superuser.py
          python manage.py runserver 0.0.0.0:8000
      ports:
        - "8080:8000"